### PR TITLE
Upgrade for fly@2

### PR DESCRIPTION
**Pull request by lukeed**

### CODE REVIEW

**Comment by lukeed** [comment]
@jbucaran earth to bucaran? lol

**Comment by jorgebucaran** [comment]
I'll merge this after I rebase to update the git history with my new email.

**Comment by lukeed** [comment]
ping @jbucaran 

Sorry, but I need this. Daily driver

**Comment by jorgebucaran** [comment]
@lukeed Done. Please rebase the PR.

**Pull request closed without merging**
