### PR TITLE
Upgrade for Fly@2 [rebased]

### PR DESCRIPTION
**Pull request by lukeed**
Same as #3

### CODE REVIEW

**Comment by lukeed** [comment]
@jbucaran (in case you don't get notifs on this repo)

**Comment by jorgebucaran** [comment]
@lukeed I wasn't. Thanks!

**Comment by lukeed** [comment]
Thanks to you sir @jbucaran.

**Comment by lukeed** [comment]
@jbucaran Please release as `2.0.0`

**Comment by lukeed** [comment]
@jbucaran ping 😶

**Comment by jorgebucaran** [comment]
@lukeed Thanks, I'll get to this as soon as I can :)

**Comment by lukeed** [comment]
@jbucaran Dude, I'm sorry. I know you have work to do, but I've waited 10 days for this to get merged. All that's left is literally a 5-10 second publish.

Here's a copy-paste to make it even faster for you:

``` bash
git clone https://github.com/flyjs/fly-uglify && cd fly-uglify
npm version major && npm publish && git push origin master --tags
```

**Comment by jorgebucaran** [comment]
@lukeed You are totally right, it's done and sorry for the delay!  🙇

**Comment by lukeed** [comment]
@jbucaran Thanks!

**Pull request merged**
