### PR TITLE
Minor tweaks to remove unused package

### PR DESCRIPTION
**Pull request by watilde**
I'd like to try [fly/example](https://github.com/flyjs/fly/tree/master/examples), but an error was displayed when I run `npm i`:

```
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/watilde/.nodebrew/current/bin/npm" "i"
npm ERR! node v0.12.0
npm ERR! npm  v3.0.0

npm ERR! No compatible version found: 0.0.1
npm ERR! Valid install targets:
npm ERR! ["0.0.3"]
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

This patch for fixing this error. Thanks!

### CODE REVIEW

**Comment by Meroje** [comment]
The latest commit on master includes this, @bucaran can we get a new version published ?

**Comment by ghost** [comment]
Done. 0.0.4 is :arrow_up:

**Comment by watilde** [comment]
Wow! Thanks as always.

**Comment by watilde** [comment]
@bucaran Could you please exec `npm version patch && npm publish` this? Currently it seems to be still error and publishing version is `v0.0.1` on the npm registry: https://www.npmjs.com/package/fly-uglify

**Comment by ghost** [comment]
@watilde Done. The plugin will get simpler with a small tweak to the plugin API in `Fly@0.0.5`, basically the `Fly.prototype.filter` function will let you add plugins by name (which let us check whether the plugin exists or not and throw an error if it does) and also write plugins 2~3 LOC _less_.

**Comment by watilde** [comment]
@bucaran Sounds so nice! Thanks amigo :smiley_cat:

> write plugins 2~3 LOC less.

**Pull request closed without merging**
